# Imagem Node para desenvolvimento
FROM node:current-alpine3.22

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia todo o código
COPY . .

# Expõe a porta do dev server do React
EXPOSE 3000

# Comando para rodar o React com hot-reload
CMD ["sh", "-c", "npm start"]
