version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app      # Sincroniza arquivos locais com o container
      - /usr/src/app/node_modules   # Mantém node_modules do container
    depends_on:
      - db
    command: ["./start.sh"]         # Espera DB, roda migrations, inicia nodemon

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # hot-reload
      - WATCHPACK_POLLING=true    # hot-reload
    depends_on:
      - backend


volumes:
  db_data:
