FROM node:current-alpine3.22

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
RUN npm install -g nodemon

# Instala pg_isready
RUN apk add --no-cache postgresql-client

COPY wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

COPY start.sh ./start.sh
RUN chmod +x ./start.sh

COPY . .

EXPOSE 8080

CMD ["./start.sh"]
